language: php
sudo: false
cache:
  directories:
    - $HOME/.composer/cache/files
matrix:
  fast_finish: true
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
before_install:
  - mkdir out
  - composer self-update
  - curl -LSs https://box-project.github.io/box2/installer.php | php
  - mv box.phar box
  - chmod 755 box
script:
  - composer install --optimize-autoloader
  - php box build
  - sha1sum out/skylab.phar > out/skylab.version
deploy:
  - provider: releases
    skip_cleanup: true
    api_key: 'make secure'
    file: out/skylab.phar
    on:
      repo: Kunstmaan/skylab
      php: 7.0
      tags: true
  - provider: s3
    access_key_id: 'make secure'
    secret_access_key: 'make secure'
    bucket: kunstmaan-skylab
    skip_cleanup: true
    acl: public_read
    region: eu-west-1
    local_dir: out
    on:
      repo: Kunstmaan/skylab
      php: 7.0
notifications:
  slack:
    secure: YPOKgHTBB/kJJCd6fsUhZxHE4TLAXWvzCGlAUT1LyTdMrIKgW2we31b24iYyNuYbb3LSTTCc1ipByh5kzjM9o+uzHvS3GbSkh8Kdn+e4b62Z+6g1TiLfFZcJi/vorPyHuUVFGhTryTBTxMwDNbQBNMxMkMxofYLfOszsBx1dOkw=
